version: "3"

services:
  app:
    build: .
    container_name: app
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    links:
      - database
    depends_on:
      - database
    networks:
      app:
        ipv4_address: 172.28.1.1
        aliases:
          - app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app
    networks:
      app:
        ipv4_address: 172.28.1.2
        aliases:
          - nginx

  database:
    image: mysql:8
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app123
    expose:
      - "3306"
    networks:
      app:
        ipv4_address: 172.28.1.3
        aliases:
          - database

networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
