api_person_list:
  path: /api/person
  methods: [GET]
  controller: App\Controller\ListPerson

api_person_view:
  path: /api/person/{id}
  methods: [GET]
  controller: App\Controller\ViewPerson

api_person_create:
  path: /api/person
  methods: [POST]
  controller: App\Controller\CreatePerson

api_person_update:
  path: /api/person/{id}
  methods: [PUT]
  controller: App\Controller\UpdatePerson

api_person_delete:
  path: /api/person/{id}
  methods: [DELETE]
  controller: App\Controller\DeletePerson

api_user_account:
  path: /api/account
  methods: [GET]
  controller: App\Controller\ViewAccount

api_login_check:
  path: /token
